In [2]:
#import necessary libraries
import numpy as np
import pandas as pd

In [4]:
# import sklearn load dataset
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [10]:
# display dataset type
type(iris_dataset)

sklearn.utils.Bunch

In [11]:
# view information using dataset built in method DESCR (describe)
iris_dataset['DESCR']

'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ============

In [12]:
# view features
iris_dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
# view target(response)
iris_dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
# find number of observations
print(iris_dataset.data.shape)

(150, 4)


In [15]:
# assign features data to X axis
X_features = iris_dataset.data

In [16]:
# assign target data to y axis
Y_target = iris_dataset.target

In [17]:
# view the shape of both axis
print(X_features.shape)
print(Y_target.shape)

(150, 4)
(150,)


In [18]:
# first use KNN classifier method - import it from sklearn
from sklearn.neighbors import KNeighborsClassifier


In [19]:
# instantiate the knn estimator
knn = KNeighborsClassifier(n_neighbors=1)

In [20]:
# print the knn
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [21]:
# fit data into knn model (estimator)
knn.fit(X_features,Y_target)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [22]:
# create objects with new values for prediction
X_new = [[3,5,4,1],[5,3,4,2]]

In [23]:
# predict the outcome for the new observation using knn classifier
knn.predict(X_new)

array([1, 1])

In [24]:
# use the logistic regression estimator
from sklearn.linear_model import LinearRegression
logReg = LinearRegression()

In [25]:
# fit data into the Logistic regression estimator
logReg.fit(X_features,Y_target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [26]:
# pridict the outcome using Logistic regression estimator
logReg.predict(X_new)

array([1.15955702, 1.63844911])